### ISSUE TITLE
Doesn't work for p/q of 5/11

### ISSUE THREAD

**Issue by RevealedFrom** [HSchmale16/RSA-React#1]
I find that it doesn't work for _p_ and _q_ of 5 and 11, no matter what I pick for _e_. Encrypting a message of 65 gives a _c_ of 10. But decrypting 10 gives 10.

According to https://math.stackexchange.com/questions/2764796/what-is-the-smallest-n-pq-for-which-the-rsa-encryption-and-decryption-works, 5/11 should work.

I am trying to find small enough numbers that can work on a calculator for demonstration purposes.

**Comment by HSchmale16** [comment]
It seems to work for me. Can you provide a screenshot?

**Comment by RevealedFrom** [comment]
![image](https://user-images.githubusercontent.com/5305957/178283369-dbdde183-2744-47e6-b872-c50587fb7e82.png)

Message of 66 gives c of 11 and decrypts to 11
Message of 67 gives c of  23 and decrypts to 12

Above is Edge. Same results in Chrome.

**Comment by HSchmale16** [comment]
I see the issue. You can't use messages that are greater than n. There's a
reason RSA is at least 1024 bits. So if you try again with numbers less
than 50 it should work perfectly.
